# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
VAGRANT_BOX = "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box"
DOMAIN = "cdh.vagrant"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = false 
    config.hostmanager.include_offline = true
    (1..3).each do |i|
        host = "hadoop#{i}"
        fqdn = "#{host}.#{DOMAIN}"
        config.vm.define fqdn do |node|
            node.vm.provider :virtualbox do |v|
                v.name = fqdn
                v.customize ["modifyvm", :id, "--memory", "2048"]
            end
            node.vm.box = VAGRANT_BOX
            node.vm.network "private_network", ip: "192.168.33.1#{i}"
            node.vm.network "public_network", type: "dhcp", bridge: "en0: Wi-Fi (AirPort)"
            node.vm.hostname = fqdn
            node.hostmanager.aliases = [host]
        end
    end
    
    config.vm.provision :puppet do |puppet|
        puppet.module_path          = "modules"
        puppet.hiera_config_path    = "hiera.yaml"
    end
end
